### ISSUE TITLE
Material test error with python 3.10

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#909]
With #907, python 3.10 is now supported.
After merging the PR I have noticed that one test is failing for this python version:

```python
________________________________ test_error_rho ________________________________

    def test_error_rho():
        with pytest.raises(TypeError) as ex:
            Material(name="test", E=203.2e9, G_s=80e9)
    
>       assert "__init__() missing 1 required positional argument: 'rho'" == str(ex.value)
E       assert "__init__() m...gument: 'rho'" == "Material.__i...gument: 'rho'"
E         - Material.__init__() missing 1 required positional argument: 'rho'
E         ? ---------
E         + __init__() missing 1 required positional argument: 'rho'
```
